# This is a basic workflow to help you get started with Actions

name: Java CI With Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3  
      
      # Runs a single command using the runners shell
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          cache: maven
      - name: Build + package with Maven
        run: mvn -B package --file ./my-app/pom.xml

      - name: Build Image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/hello-maven .

      - name: Step 6 - Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{secrets.DOCKERHUB_USERNAME}}'
          password: '${{secrets.DOCKERHUB_TOKEN}}'

      - name: Push to Dockerfile
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/hello-maven
